Models/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace ManejoPresupuestos.Models
{
    public class LoginViewModel
    {
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [EmailAddress(ErrorMessage = "El campo debe ser un correo electronico valido")]
        public string Email { get; set; }
        [Required(ErrorMessage = "El campo {0} es requerido")]

        public string Password { get; set; }

        public bool Recuerdame { get; set; }
    }
}

Models/OlvideMiPasswordViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace ManejoPresupuestos.Models
{
    public class OlvideMiPasswordViewModel
    {
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [EmailAddress(ErrorMessage = "El campo debe ser un correo electronico valido")]
        public string Email { get; set; }
    }
}

Models/RecuperarPasswordViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace ManejoPresupuestos.Models
{
    public class RecuperarPasswordViewModel
    {
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [EmailAddress(ErrorMessage = "El campo debe ser un correo electrónico válido")]
        public string Email { get; set; }
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        public string CodigoReseteo { get; set; }
    }
}

Models/RegistroViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace ManejoPresupuestos.Models
{
    public class RegistroViewModel
    {
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [EmailAddress(ErrorMessage = "El campo debe ser un correo electronico valido")]
        public string Email { get; set; }
        [Required(ErrorMessage = "El campo {0} es requerido")]

        public string Password { get; set; }
    }
}

Models/Usuario.cs
using System.ComponentModel.DataAnnotations;

namespace ManejoPresupuestos.Models
{
    public class Usuario
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [EmailAddress(ErrorMessage = "El campo debe ser un correo electronico valido")]
        public string Email { get; set; }
        [Required(ErrorMessage = "El campo {0} es requerido")]
        public string EmailNormalizado { get; set; }
        public string PasswordHash { get; set; }
    }
}

Controllers/PrincipalController.cs
using ManejoPresupuestos.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ManejoPresupuestos.Controllers
{
    public class PrincipalController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public PrincipalController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
        [AllowAnonymous]
        public IActionResult Index()
        {
            return View();
        }

        
    }
}

Controllers/UsuariosController.cs
using ManejoPresupuestos.Models;
using ManejoPresupuestos.Servicios;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.WebUtilities;
using System.Text;

namespace ManejoPresupuestos.Controllers
{
    public class UsuariosController: Controller
    {
        private readonly UserManager<Usuario> userManager;
        private readonly SignInManager<Usuario> signInManager;
        private readonly IServicioEmail servicioEmail;

        public  UsuariosController(UserManager<Usuario> userManager,
            SignInManager<Usuario> signInManager, IServicioEmail ServicioEmail)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
            servicioEmail = ServicioEmail;
        }
      
        [AllowAnonymous]
        public IActionResult Registro()
        {
            return View();
        }
        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Registro(RegistroViewModel modelo)
        {
       
            if (!ModelState.IsValid)
            {
                return View(modelo);
                //Asignando la Cookie al usuario

                
            }

            var usuario = new Usuario() { Email = modelo.Email };

            var resultado = await userManager.CreateAsync(usuario, password: modelo.Password);

            if (resultado.Succeeded)
            {
               await signInManager.SignInAsync(usuario, isPersistent: true);
                return RedirectToAction("Index", "Transacciones");
            }
            else
            {
                foreach (var error in resultado.Errors)
                {
                    ModelState.TryAddModelError(string.Empty, error.Description);
                }

                return View(modelo);
            }

        }

       

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Login()
        {

            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Login(LoginViewModel modelo)
        {
            if (!ModelState.IsValid)
            {
                return View(modelo);
            }

            var resultado = await signInManager.PasswordSignInAsync(modelo.Email,
                modelo.Password, modelo.Recuerdame, lockoutOnFailure: false);
            if (resultado.Succeeded)
            {
                return RedirectToAction("Index", "Transacciones");

            }
            else
            {
                ModelState.AddModelError(string.Empty, "Nombre de usuario o clave incorrecto. ");
                return View(modelo);
            }

        }

        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(IdentityConstants.ApplicationScheme);
            return RedirectToAction("Index", "Transacciones");
        }

        [HttpGet]
        [AllowAnonymous]

        public IActionResult OlvideMiPassword(string mensaje = "")
        {
            ViewBag.Mensaje = mensaje;
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> OlvideMiPassword(OlvideMiPasswordViewModel modelo)
        {
            var mensaje = "Proceso concluido. Si el email dado se corresponde con uno de nuestros usuarios, en su bandeja podra encontrar las instrucciones para recuperar su contraseña.";
            ViewBag.Mensaje = mensaje;
            ModelState.Clear();

            var usuario = await userManager.FindByEmailAsync(modelo.Email);

            if(usuario is null)
            {
                return View();
            }

            var codigo = await userManager.GeneratePasswordResetTokenAsync(usuario);
            var codigoBase64 = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(codigo));
            var enlace = Url.Action("RecuperarPassword", "Usuarios", new { codigo = codigoBase64 },
                protocol: Request.Scheme);
            await servicioEmail.EnviarEmailCambioPassword(modelo.Email, enlace);
            return View();
                
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult RecuperarPassword(string codigo = null)
        {
            if (codigo is null)
            {
                var mensaje = "Código no encontrado";
                return RedirectToAction("OlvideMiPassword", new { mensaje });
            }

            var modelo = new RecuperarPasswordViewModel();
            modelo.CodigoReseteo = Encoding.UTF8.GetString(WebEncoders.Base64UrlDecode(codigo));
            return View(modelo);
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> RecuperarPassword(RecuperarPasswordViewModel modelo)
        {
            var usuario = await userManager.FindByEmailAsync(modelo.Email);

            if (usuario is null)
            {
                return RedirectToAction("PasswordCambiado");
            }

            var resultados = await userManager.ResetPasswordAsync(usuario, modelo.CodigoReseteo,
                modelo.Password);
            return RedirectToAction("PasswordCambiado");
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult PasswordCambiado()
        {
            return View();
        }
       
    }
}

Views/Usuarios/Login.cshtml
@model LoginViewModel

@{
    ViewData["Title"] = "Inicio";
}
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">

         

    </nav>
</header>
<h1 class="text-center">Inicio de Sesión</h1>

@if (ViewData.Keys.Contains("mensaje"))
{
    <div class="alert alert-danger" role="alert">
        @ViewData["mensaje"]
    </div>
}

<div class="card mx-auto" style="max-width: 400px; box-shadow: 0 0 15px rgba(0, 0, 0, 0.1); border-radius: 10px;">
    <div class="card-body p-4">
        <form class="form" asp-action="Login">
            <div asp-validation-summary="ModelOnly" class="text-danger mb-3"></div>
            <p class="title">Login </p>
            <div class="form-group mb-3">
                <label asp-for="Email" class="form-label"></label>
                <input asp-for="Email" autocomplete="off" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label asp-for="Password" class="form-label">Password</label>
                <div class="input-group">
                    <input asp-for="Password" id="password" type="password" class="form-control" />
                    <button class="btn btn-outline-secondary" type="button" onclick="togglePasswordVisibility()">
                        <img id="toggle-icon" src="https://img.icons8.com/ios-glyphs/30/000000/visible.png" alt="Show/Hide Password" style="margin-left: 5px;" />
                    </button>
                </div>
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>

            <div class="form-check mb-3">
                <input class="form-check-input" type="checkbox" asp-for="Recuerdame" />
                <label class="form-check-label" asp-for="Recuerdame"></label>
            </div>

            <div class="d-grid">
                <button type="submit" class="btn btn-primary">Login</button>
            </div>

            <div class="d-grid mt-3">
                <a class="btn btn-success" asp-action="Registro">Crear una nueva cuenta</a>
            </div>

            <!-- Enlace para restablecer la contraseña -->
            <div class="d-grid mt-3 texr-center">
                <a class="btn" asp-action="OlvideMiPassword">¿Olvidaste tu contraseña?</a>
            </div>


            <div class="d-grid mt-4">
                <a class="btn btn-secondary" asp-controller="Principal" asp-action="Index">Cancelar</a>
            </div>
            
        </form>
    </div>
</div>



<script>
    function togglePasswordVisibility() {
        var passwordField = document.getElementById("password");
        var toggleIcon = document.getElementById("toggle-icon");
        if (passwordField.type === "password") {
            passwordField.type = "text";
            toggleIcon.src = "https://img.icons8.com/ios-glyphs/30/000000/invisible.png";
        } else {
            passwordField.type = "password";
            toggleIcon.src = "https://img.icons8.com/ios-glyphs/30/000000/visible.png";
        }
    }
</script>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Views/Usuarios/OlvideMiPassword.cshtml
@model OlvideMiPasswordViewModel
@{
    ViewData["Title"] = "¿Olvidaste tu contraseña";
}
<h1>Recuperar tu cuenta</h1>

<div class="card">
    <div class="card-body">
        <p class="fw-bold">@ViewBag.Mensaje</p>

        <form asp-action="OlvideMiPassword">
            <div asp-validation-summary="ModelOnly"class="text-danger"></div>

            <div class="mb-3">
                <label asp-for="Email" class="form-label"></label>
                <input asp-for="Email" class="form-control"/>
                <span -asp-validation-for="Email" class="text-danger"></span>

            </div>
            <a class="btn btn-secondary"asp-action="login">Cancelar</a>
            <button class="btn btn-primary">Recuperar</button>
        </form>
    </div>
</div>

Views/Usuarios/PasswordCambiado.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Password actualizado";
}

<p>
    Password actualizado. Haz <a asp-action="login">click aquí para loguearte</a>.
</p>

Views/Usuarios/RecuperarPassword.cshtml
@model RecuperarPasswordViewModel

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Resetea tu password";
}

<h1>Resetea tu password</h1>

<div class="card">
    <div class="card-body">
        <form asp-action="RecuperarPassword">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CodigoReseteo" />

            <div class="mb-3">
                <label asp-for="Email" class="form-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label asp-for="Password" class="form-label">Password</label>
                <div class="input-group">
                    <input asp-for="Password" id="password" type="password" class="form-control" />
                    <button class="btn btn-outline-secondary" type="button" onclick="togglePasswordVisibility()">
                        <img id="toggle-icon" src="https://img.icons8.com/ios-glyphs/30/000000/visible.png" alt="Show/Hide Password" style="margin-left: 5px;" />
                    </button>
                </div>
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>

            <button class="btn-primary btn">Resetear</button>
        </form>
    </div>

    <script>
        function togglePasswordVisibility() {
            var passwordField = document.getElementById("password");
            var toggleIcon = document.getElementById("toggle-icon");
            if (passwordField.type === "password") {
                passwordField.type = "text";
                toggleIcon.src = "https://img.icons8.com/ios-glyphs/30/000000/invisible.png";
            } else {
                passwordField.type = "password";
                toggleIcon.src = "https://img.icons8.com/ios-glyphs/30/000000/visible.png";
            }
        }
    </script>

</div>

Views/Usuarios/Registro.cshtml
@model RegistroViewModel

@{
    ViewBag.Title = "Registro";
}

<div class="card mx-auto" style="max-width: 400px; box-shadow: 0 0 15px rgba(0, 0, 0, 0.1); border-radius: 10px; margin: 50px auto; padding: 20px;">
    <div class="card-body">


        <form class="form" asp-action="Registro">
            <div asp-validation-summary="ModelOnly" class="text-danger mb-3"></div>

            <p class="title">Registate </p>

             <div class="mb-3">
                <label asp-for="Email" class="form-label"></label>
                <input asp-for="Email" autocomplete="off" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="Password" class="form-label">Password</label>
                <div class="input-group">
                    <input asp-for="Password" id="password" type="password" class="form-control" />
                    <button class="btn btn-outline-secondary" type="button" onclick="togglePasswordVisibility()">
                        <img id="toggle-icon" src="https://img.icons8.com/ios-glyphs/30/000000/visible.png" alt="Show/Hide Password" style="margin-left: 5px;" />
                    </button>
                </div>
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>

            <div class="d-grid mt-4">
                <button type="submit" class="btn btn-primary">Regístrate</button>
            </div>

            <div class="d-grid mt-4">
                <a class="btn btn-secondary" asp-controller="Principal" asp-action="Index">Cancelar</a>
            </div>

           
        </form>
    </div>
</div>

<script>
    function togglePasswordVisibility() {
        var passwordField = document.getElementById("password");
        var toggleIcon = document.getElementById("toggle-icon");
        if (passwordField.type === "password") {
            passwordField.type = "text";
            toggleIcon.src = "https://img.icons8.com/ios-glyphs/30/000000/invisible.png";
        } else {
            passwordField.type = "password";
            toggleIcon.src = "https://img.icons8.com/ios-glyphs/30/000000/visible.png";
        }
    }
</script>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Views/Usuarios/_layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ManejoPresupuestos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ManejoPresupuestos.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/custom.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="ManejoPresupuestos.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="ManejoPresupuestos.styles.css" asp-append-version="true" />
  
</head>
<body>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>