Controllers/ProyectoController.cs
using ManejoPresupuestos.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ManejoPresupuestos.Controllers
{
    public class ProyectoController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public ProyectoController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
        [AllowAnonymous]
        public IActionResult Index()
        {
            return View();
        }

        
    }
}

Views/Directiva/Index.cshtml
@{
    ViewData["Title"] = "Directiva";
}


<h1 class="text-center">Nuestra Directiva</h1>

<nav custom-navbar class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container-fluid">
        <ul class="navbar-nav flex-grow-1">
            <li class="nav-item">
                <a class="nav-item" asp-controller="Principal" asp-action="Index">Inicio</a>
            </li>

            <li class="nav-item">
                <a class="nav-item" asp-controller="Proyecto" asp-action="Index">Proyectos</a>
            </li>
        </ul>
       
    </div>
    
</nav>

<div class="contenedor-flex">
    <div class="flip-card">
        <div class="flip-card-inner">
            <div class="flip-card-front">
                <p class="title-card">Directiva</p>
                <p>Ver</p>
            </div>
            <div class="flip-card-back">
                <p class="title-card">Foto</p>
                <img id="foto" src="~/imagenes/avatar.png" alt="Foto presidente" />
                <p>Jose Varela</p>
            </div>
        </div>
    </div>
 
    <div class="flip-card">
        <div class="flip-card-inner">
            <div class="flip-card-front">
                <p class="title-card">Directiva</p>
                <p>Ver</p>
            </div>
            <div class="flip-card-back">
                <p class="title-card">Foto</p>
                <img id="foto" src="~/imagenes/avatar2.png" alt="Foto presidente" />
                <p>Jose Varela</p>
            </div>
        </div>
    </div>

    <div class="flip-card">
        <div class="flip-card-inner">
            <div class="flip-card-front">
                <p class="title-card">Directiva</p>
                <p>Ver</p>
            </div>
            <div class="flip-card-back">
                <p class="title-card">Foto</p>
                <img id="foto" src="~/imagenes/avatar3.png" alt="Foto presidente" />
                <p>Jose Varela</p>
            </div>
        </div>
    </div>

    <div class="flip-card">
        <div class="flip-card-inner">
            <div class="flip-card-front">
                <p class="title-card">Directiva</p>
                <p>Ver</p>
            </div>
            <div class="flip-card-back">
                <p class="title-card">Foto</p>
                <img id="foto" src="~/imagenes/avatar4.png" alt="Foto presidente" />
                <p>Jose Varela</p>
            </div>
        </div>
    </div>

 
</div>

<div class="contenedor-flex">

    <div class="flip-card">
        <div class="flip-card-inner">
            <div class="flip-card-front">
                <p class="title-card">Directiva</p>
                <p>Ver</p>
            </div>
            <div class="flip-card-back">
                <p class="title-card">Foto</p>
                <img id="foto" src="~/imagenes/avatar5.png" alt="Foto presidente" />
                <p>Jose Varela</p>
            </div>
        </div>
    </div>

    <div class="flip-card">
        <div class="flip-card-inner">
            <div class="flip-card-front">
                <p class="title-card">Directiva</p>
                <p>Ver</p>
            </div>
            <div class="flip-card-back">
                <p class="title-card">Foto</p>
                <img id="foto" src="~/imagenes/avatar6.png" alt="Foto presidente" />
                <p>Jose Varela</p>
            </div>
        </div>
    </div>

    <div class="flip-card">
        <div class="flip-card-inner">
            <div class="flip-card-front">
                <p class="title-card">Directiva</p>
                <p>Ver</p>
            </div>
            <div class="flip-card-back">
                <p class="title-card">Foto</p>
                <img id="foto" src="~/imagenes/avatar7.png" alt="Foto presidente" />
                <p>Jose Varela</p>
            </div>
        </div>
    </div>

    <div class="flip-card">
        <div class="flip-card-inner">
            <div class="flip-card-front">
                <p class="title-card">Directiva</p>
                <p>Ver</p>
            </div>
            <div class="flip-card-back">
                <p class="title-card">Foto</p>
                <img id="foto" src="~/imagenes/avatar8.png" alt="Foto presidente" />
                <p>Jose Varela</p>
            </div>
        </div>
    </div
</div>