Controllers/TiposCuentasController.cs
using ManejoPresupuestos.Models;
using ManejoPresupuestos.Servicios;
using Microsoft.AspNetCore.Mvc;

namespace ManejoPresupuestos.Controllers
{
    public class TiposCuentasController : Controller
    {
        private readonly IRepositorioTiposCuentas repositorioTiposCuentas;
        private readonly IServicioUsuarios servicioUsuarios;

        public TiposCuentasController(IRepositorioTiposCuentas repositorioTiposCuentas,
           IServicioUsuarios servicioUsuarios)
        {
            this.repositorioTiposCuentas = repositorioTiposCuentas;
            this.servicioUsuarios = servicioUsuarios;
        }

        public async Task<IActionResult> Index()
        {
            var usuarioId = servicioUsuarios.ObtenerUsuarioId();
            var tiposCuentas = await repositorioTiposCuentas.Obtener(usuarioId);
            return View(tiposCuentas);
        }

        public IActionResult Crear()
        {

            return View();
        }

        [HttpPost]

        /* Mostrar los errores*/
        public async Task <IActionResult> Crear(TipoCuenta tipoCuenta)

        {
            /*Esta es la logica del codigo 
             * y donde validamos la informacion que viene de los usuarios.*/
            if (!ModelState.IsValid)
            {
                return View(tipoCuenta);
            }
            tipoCuenta.UsuarioId = servicioUsuarios.ObtenerUsuarioId();

            var yaExisteTipoCuenta = 
                await repositorioTiposCuentas.Existe(tipoCuenta.Nombre, tipoCuenta.UsuarioId);

            if (yaExisteTipoCuenta)
            {
                ModelState.AddModelError(nameof(tipoCuenta.Nombre),
                $"El Nombre {tipoCuenta.Nombre} ya existe");

                return View(tipoCuenta);
            }
         
            await repositorioTiposCuentas.Crear(tipoCuenta);

            return RedirectToAction("Index");
        }

        [HttpGet]

        public async Task<IActionResult> Editar(int id)
        {
            var usuarioId = servicioUsuarios.ObtenerUsuarioId();
            var tipoCuenta = await repositorioTiposCuentas.ObtenerPorId(id, usuarioId);
            if (tipoCuenta is null)
            {
                return RedirectToAction("NoEncontrado", "Home"); ;
            }
            return View(tipoCuenta);
        }

        [HttpPost]
        public async Task<IActionResult> Editar(TipoCuenta tipoCuenta)
        {
            var usuarioId = servicioUsuarios.ObtenerUsuarioId();
            var tipoCuentaExiste = await repositorioTiposCuentas.ObtenerPorId(tipoCuenta.Id, usuarioId);
            if (tipoCuentaExiste is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }
            await repositorioTiposCuentas.Actualizar(tipoCuenta);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Borrar(int id)
        {
            var usuarioId = servicioUsuarios.ObtenerUsuarioId();
            var tipoCuenta = await repositorioTiposCuentas.ObtenerPorId(id, usuarioId);
            if (tipoCuenta is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }
            return View(tipoCuenta);
        }

        [HttpPost]
        public async Task<IActionResult> BorrarTipoCuenta(int id)
        {
            var usuarioId = servicioUsuarios.ObtenerUsuarioId();
            var tipoCuenta = await repositorioTiposCuentas.ObtenerPorId(id, usuarioId);
            if (tipoCuenta is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }
            await repositorioTiposCuentas.Borrar(id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> VerificarExisteTipoCuenta(string nombre)
        {
            var usuarioId = servicioUsuarios.ObtenerUsuarioId();
            var yaExisteTipoCuenta = await repositorioTiposCuentas.Existe(nombre, usuarioId);
            if (yaExisteTipoCuenta)
            {
                return Json($"El nombre {nombre} ya existe");
            }
            return Json(true);
        }

        [HttpPost]
        public async Task<IActionResult> Ordenar([FromBody] int[] ids)
        {
            var usuarioId = servicioUsuarios.ObtenerUsuarioId();
            var tiposCuentas = await repositorioTiposCuentas.Obtener(usuarioId);
            var idsTiposCuentas = tiposCuentas.Select(x => x.Id);

            var idsTiposCuentasNoPertenecenAlUsuario = ids.Except(idsTiposCuentas).ToList();

            if (idsTiposCuentasNoPertenecenAlUsuario.Count > 0)
            {
                return Forbid();
            }
            var tiposCuentasOrdenados = ids.Select((valor, indice) => 
            new TipoCuenta() { Id = valor, Orden = indice + 1 }).AsEnumerable();
            await repositorioTiposCuentas.Ordenar(tiposCuentasOrdenados);

            return Ok();
        }

    }

}


  

Views/TiposCuentas/Borrar.cshtml
@model TipoCuenta
@{
    ViewData["Title"] = "Borrar tipo cuenta";
}

<h3 class="mb-3">¿Estas seguro de que deseas borrar el tipo de cuenta @Model.Nombre? </h3>
<form asp-action="BorrarTipoCuenta">
    <input type="hidden" asp-for="Id" />
    <button type="submit" class="btn btn-danger">Borrar</button>
    <a  class="btn btn-secondary" asp-action="Index">Cancelar</a>

</form>

Views/TiposCuentas/Crear.cshtml
@model TipoCuenta
@{
    ViewData["Title"] = "Crear Tipo Cuenta";
}

<!-- Esta es la vista de los tipos cuentas -->
<!-- Los estilos de esta pagina estan en wwwroot Cuentas -->


<h5>El tipo de cuenta se refiere a cómo podemos agrupar cuentas.
    Ejemplos: Prestamos, tarjetas de crédito, etc.
</h5>
<div asp-validation-summary="ModelOnly"class="text-danger"></div>
<div class="row">
    <div class="offset-12">
        <div class="card border">
            <div class="card-header bg-dark">
                <h3 class="text-white"><strong>Crear Tipo Cuenta Nueva</strong></h3>
            </div>
            <div class="card-body">
                    <form asp-controller="TiposCuentas" asp-action="Crear">
   
                        <!--Se usa Tag helpers agregando asp-for-->
                        <div class="mb-3">

                            <label asp-for="Nombre" class="form-label"></label>
                            <input type="text" asp-for="Nombre" class="form-control" placeholder="Crear cuenta" />
                            <span asp-validation-for="Nombre" class="text-danger"></span>
                        </div>
 
                        <button type="submit" class="btn btn-primary">Enviar</button>
                        <a class="btn btn-secondary" asp-action="Index">Cancelar</a>

                    </form>

            </div>
        </div>
    </div>
</div>

@section scripts {
    <partial name="_ValidationScriptsPartial" />
}

Views/TiposCuentas/Editar.cshtml
@model TipoCuenta
@{
    ViewData["Title"] = "Editar Tipo de Cuenta";
}
<h1>Editar Tipo Cuenta: @Model.Nombre</h1>
<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<form asp-action="Editar">
    <input type="hidden" asp-for="Id" />
    <div class="mb-3">
        <label asp-for="Nombre" class="form-label"></label>
        <input type="text" asp-for="Nombre" class="form-control" />
        <span asp-validation-for="Nombre" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Enviar</button>
    <a class="btn btn-secondary" asp-action="Index">Cancelar</a>
</form>

@section scripts {
    <partial name="_ValidationScriptsPartial" />
}

Views/TiposCuentas/Index.cshtml
@model IEnumerable<TipoCuenta>

@{

    ViewData["Title"] = "Tipos Cuentas";
}

<h1>Tipos Cuentas</h1>
<h5>El tipo de cuenta se refiere a cómo podemos agrupar cuentas. Ejemplos: Préstamos, tarjetas de crédito, etc.</h5>
<a asp-action="Crear" asp-controller="TiposCuentas" class="btn btn-primary mb-3"><i class="fa fa-user" aria-hidden="true"></i> Crear nuevo</a>

<table class="table">
    <thead>
        <tr>
            <th>Acciones</th>
            <th>Nombre</th>
        </tr>
    </thead>
    <tbody id="reordenable">
        @foreach (var tipoCuenta in Model)
        {
            <tr>
                <td>
                    <input type="hidden" value="@tipoCuenta.Id" class="ids" />
                    <a asp-action="Editar" asp-controller="TiposCuentas" asp-route-id="@(tipoCuenta.Id)" class="btn btn-primary"><i class="fa fa-pencil" aria-hidden="true"></i>Editar</a>
                    <a asp-action="Borrar" asp-controller="TiposCuentas" asp-route-id="@(tipoCuenta.Id)" class="btn btn-danger"><i class="fa fa-eraser" aria-hidden="true"></i>Borrar</a>
                </td>
                <td>
                    @tipoCuenta.Nombre
                </td>
            </tr>
        }
    </tbody>

</table>
@section Scripts{
    <script>
        const urlOrdenar = '@Url.Action("Ordenar","TiposCuentas")';
        $(function () {
            $('#reordenable').sortable({
                stop: async function (e, ui) {
                    await actualizarOrdenes();
                }
            });
            async function actualizarOrdenes() {
                const ids = obtenerIdsDeElementos();
                await enviarIdsAlBackEnd(ids);
            }
            function obtenerIdsDeElementos() {
                const ids = $(".ids").map(function () {
                    return $(this).val();
                }).get();
                return ids;
            }
            async function enviarIdsAlBackEnd(ids) {
                var data = JSON.stringify(ids);
                await fetch(urlOrdenar, {
                    method: 'POST',
                    body: data,
                    headers: {
                        'Content-Type': 'application/json'
                    }
                });
            }
        })
    </script>
}